### ISSUE TITLE
Don´t working on RG35XX H

### ISSUE THREAD

**Issue by dual3zw** [haoict/SimpleTerminal#2]
Congratulations by the app. It opens, but don´t accept any command. I've tested on last stock firmare version, RG35XXH-V1.1.4-EN16GB-240626.

**Comment by haoict** [comment]
From v1.1.3 they updated the controller key mapping. I'll work on the update once I have time soon

**Comment by dual3zw** [comment]
> From v1.1.3 they updated the controller key mapping. I'll work on the update once I have time soon

Ohh, thanks for the quickly reply! I was think if my RG35XX H was problematic. I already try to connect a USB keyboard via OTG but without success. Know you if there's a way to access a pure TTY terminal on RG35XX family? I do that on R36S.

**Comment by haoict** [comment]
the module fbcon (Framebuffer Console) is disabled in the Rg35xx- devices kernel. Since Anbernice hasn't published source code of the stock kernel, there's currently no way to use standard TTY like R36S :(

**Comment by haoict** [comment]
New version released, now supports stock OS version 1.1.3 and up

https://github.com/haoict/SimpleTerminal/releases/tag/1.0.0-rg35xx-plush
