### ISSUE TITLE
r36s support?

### ISSUE THREAD

**Issue by SlyBouhafs** [haoict/SimpleTerminal#5]
Does it work with the R36S console by any chance? i don't see a build for it.

**Comment by haoict** [comment]
there's a build for r36s but I haven't released it yet. I'll upload soon

**Comment by SlyBouhafs** [comment]
@haoict That's awesome! Thanks!! Can you update the readme on how to build for the r36s as well?

**Comment by SlyBouhafs** [comment]
@haoict Any updates?

**Comment by haoict** [comment]
@SlyBouhafs 
sorry for the delay. I uploaded the binary here: https://github.com/haoict/SimpleTerminal/releases/tag/1.4.0
let me know if it works
